In [2]:
pip install tensorflow

  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached protobuf-5.29.1-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
  Using cached termcolor-2.5.0-py3-none-any.whl.metadata (6.1 kB)
  Using cached tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
  Using cached keras-3.7.0-py3-none-any.whl.metadata (5.8 kB)
  Using cached rich-13.9.4-py3-none-any.whl.metadata (18 kB)
  Using cached namex-0.0.8-py3-none-any.whl.metadata (246 bytes)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
  Using cached Markdown

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent =['As twilight paints the sky in gold',
'The sun dips low, the day grows old',
'Shadows dance on silken breeze',
'Whispering secrets through the trees',

'Stars emerge with timid light',
'Guardians of the quiet night',
'Moonbeams weave a silver thread',
'Guiding dreams where hearts are led',]

In [6]:
sent

['As twilight paints the sky in gold',
 'The sun dips low, the day grows old',
 'Shadows dance on silken breeze',
 'Whispering secrets through the trees',
 'Stars emerge with timid light',
 'Guardians of the quiet night',
 'Moonbeams weave a silver thread',
 'Guiding dreams where hearts are led']

In [7]:
vocab_sent = 10000

In [8]:
# one_hot encoding
one_hot_encod= [one_hot(words, vocab_sent) for words in sent]

In [10]:
# index number of each word
one_hot_encod

[[9511, 6482, 8998, 2076, 1851, 4972, 2766],
 [2076, 7675, 4659, 4148, 2076, 9163, 7182, 5265],
 [4836, 6361, 2039, 7660, 4796],
 [7818, 9043, 7919, 2076, 865],
 [6010, 5149, 5589, 4345, 611],
 [4994, 8113, 2076, 312, 6428],
 [5767, 223, 6846, 534, 423],
 [2153, 4763, 7632, 9501, 4328, 1118]]

N.B: After one hot encoding, every word of every sentence will have 10000 dimensions, where only the word index value will be 1, and the rest of 9999 will be 0. So, it makes a sparse matrix, and overfitting will be present. That's why we are focusing on the embedding layer.

# word Embedding representation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [15]:
sent_length =10
embedded_docs = pad_sequences(one_hot_encod, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 9511 6482 8998 2076 1851 4972 2766]
 [   0    0 2076 7675 4659 4148 2076 9163 7182 5265]
 [   0    0    0    0    0 4836 6361 2039 7660 4796]
 [   0    0    0    0    0 7818 9043 7919 2076  865]
 [   0    0    0    0    0 6010 5149 5589 4345  611]
 [   0    0    0    0    0 4994 8113 2076  312 6428]
 [   0    0    0    0    0 5767  223 6846  534  423]
 [   0    0    0    0 2153 4763 7632 9501 4328 1118]]


In [16]:
# Feature representation
dim = 10

In [18]:
model = Sequential()
model.add(Embedding(vocab_sent, dim, input_length =sent_length))
model.compile('adam', 'mse')

/workspaces/GenerativeAI_Langchain_Huggingface/venv/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2024-12-07 17:26:16.502713: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [19]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step


array([[-0.03084074, -0.01663197, -0.01786504,  0.00157795,  0.0426381 ,
         0.02247042, -0.01675714,  0.0483712 ,  0.01613693,  0.03854075],
       [-0.03084074, -0.01663197, -0.01786504,  0.00157795,  0.0426381 ,
         0.02247042, -0.01675714,  0.0483712 ,  0.01613693,  0.03854075],
       [-0.03084074, -0.01663197, -0.01786504,  0.00157795,  0.0426381 ,
         0.02247042, -0.01675714,  0.0483712 ,  0.01613693,  0.03854075],
       [-0.01169465,  0.04750684, -0.02441256, -0.01638127, -0.00128452,
         0.00708724, -0.02469841,  0.017649  , -0.04001224, -0.00741459],
       [-0.03157226, -0.0385888 , -0.02627434, -0.02840918,  0.04943553,
        -0.00204827,  0.02935454, -0.00423378,  0.02909604,  0.03273792],
       [ 0.0473437 ,  0.03786853,  0.00413823, -0.01531432,  0.02434171,
        -0.03722948,  0.01122461,  0.01758244, -0.0040314 , -0.03709411],
       [ 0.04949361, -0.00975137,  0.00302789, -0.01840799,  0.0265241 ,
         0.0020416 ,  0.00964699,  0.02775917